/**
 * galleryImages.js — Eleventy global data file
 * Scans every gallery category, reads EXIF via sharp + exif-reader,
 * and returns an array used by src/gallery/image.njk pagination
 * to generate one detail page per image.
 */

import sharp from 'sharp';
import exifReader from 'exif-reader';
import fs from 'node:fs';
import path from 'node:path';

const GALLERY_ROOT = './src/_gallery_source';
const IMAGE_RE = /\.(jpe?g|png|webp)$/i;

function getCategories() {
  try {
    if (fs.existsSync(GALLERY_ROOT)) {
      return fs.readdirSync(GALLERY_ROOT).filter((f) => {
        return fs.statSync(path.join(GALLERY_ROOT, f)).isDirectory();
      });
    }
  } catch (e) {
    console.error('Error reading gallery categories: ', e);
  }
  return ['photography', 'ai', 'forza'];
}

function formatFileSize(bytes) {
  return bytes >= 1024 * 1024
    ? `${(bytes / (1024 * 1024)).toFixed(1)} MB`
    : `${Math.round(bytes / 1024)} KB`;
}

function formatShutterSpeed(expTime) {
  if (!expTime) {
    return '';
  }
  if (expTime >= 1) {
    return `${expTime}s`;
  }
  const denom = Math.round(1 / expTime);
  return `1/${denom}s`;
}

/** Parse an EXIF date string "YYYY:MM:DD HH:MM:SS" or Date object into a JS Date */
function parseExifDate(str) {
  if (!str) {
    return null;
  }
  if (str instanceof Date) {
    return str;
  }
  const s = str.toString();
  if (s.includes(':') && s.includes(' ')) {
    const [datePart, timePart] = s.split(' ');
    const [y, m, d] = datePart.split(':');
    const parsed = new Date(`${y}-${m}-${d}T${timePart || '00:00:00'}`);
    return isNaN(parsed.getTime()) ? null : parsed;
  }
  const parsed = new Date(s);
  return isNaN(parsed.getTime()) ? null : parsed;
}

function formatDate(date, long = false) {
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: long ? 'long' : 'short',
    day: 'numeric',
  });
}

let cachedGalleryImagesResult = null;

export default async function () {
  if (cachedGalleryImagesResult) {
    return cachedGalleryImagesResult;
  }

  const categories = getCategories();
  const categoryPromises = categories.map(async (category) => {
    const dir = path.join(GALLERY_ROOT, category);
    if (!fs.existsSync(dir)) {
      return [];
    }

    const files = fs
      .readdirSync(dir)
      .filter((f) => IMAGE_RE.test(f))
      .sort((a, b) => {
        const na = parseInt(a, 10);
        const nb = parseInt(b, 10);
        return isNaN(na) || isNaN(nb) ? a.localeCompare(b) : na - nb;
      });

    const filePromises = files.map(async (file) => {
      const srcPath = path.join(GALLERY_ROOT, category, file);
      const baseName = path.basename(file, path.extname(file));
      const slug = `${category}-${baseName}`;

      const [meta, stats] = await Promise.all([
        sharp(srcPath).metadata(),
        fs.promises.stat(srcPath),
      ]);

      const fileSize = formatFileSize(stats.size);
      const resolution = `${meta.width} × ${meta.height}`;

      // ── EXIF ────────────────────────────────────────────────────────────
      let date = '';
      let device = '';
      let lens = '';
      let shutterSpeed = '';
      let aperture = '';
      let iso = '';
      let focalLength = '';

      const fileDate = stats.birthtime < stats.mtime ? stats.birthtime : stats.mtime;
      let resolvedDate = fileDate;

      if (meta.exif) {
        try {
          const exif = exifReader(meta.exif);
          const img = exif.Image ?? {};
          const photo = exif.Photo ?? {};

          // Device
          const make = img.Make?.trim() ?? '';
          const model = img.Model?.trim() ?? '';
          if (make && model) {
            device = model.toLowerCase().startsWith(make.toLowerCase())
              ? model
              : `${make} ${model}`;
          } else {
            device = model || make;
          }

          // Lens
          lens = photo.LensModel?.trim() || img.LensMake?.trim() || '';

          // Camera settings
          shutterSpeed = formatShutterSpeed(photo.ExposureTime);
          if (photo.FNumber) {
            aperture = `f/${photo.FNumber}`;
          }
          const isoVal = Array.isArray(photo.ISOSpeedRatings)
            ? photo.ISOSpeedRatings[0]
            : photo.ISOSpeedRatings;
          if (isoVal) {
            iso = `ISO ${isoVal}`;
          }
          if (photo.FocalLength) {
            focalLength = `${photo.FocalLength}mm`;
          }

          // Date — prefer oldest of EXIF date and file date
          const exifDate =
            parseExifDate(photo.DateTimeOriginal) ??
            parseExifDate(photo.DateTimeDigitized) ??
            parseExifDate(img.DateTime);
          resolvedDate = exifDate && exifDate < fileDate ? exifDate : fileDate;
          date = formatDate(resolvedDate, true);
        } catch {
          date = formatDate(fileDate, true);
        }
      } else {
        date = formatDate(fileDate, true);
      }

      // Thumbnail URL uses the 800w WebP generated by eleventy-img
      // Full-res display/download URL = largest generated JPEG width that
      // actually exists (eleventy-img skips widths larger than the original)
      const GENERATED_WIDTHS = [400, 800, 1200, 1800];
      const largestWidth =
        [...GENERATED_WIDTHS].reverse().find((w) => w <= meta.width) ?? GENERATED_WIDTHS[0];
      const thumbUrl = `/assets/img/gallery/${category}/${baseName}-800w.webp`;
      const webpUrl = `/assets/img/gallery/${category}/${baseName}-${largestWidth}w.webp`;
      const fullUrl = `/assets/img/gallery/${category}/${baseName}-${largestWidth}w.jpeg`;

      return {
        slug,
        category,
        filename: file,
        thumbUrl,
        webpUrl,
        fullUrl,
        downloadFilename: file,
        resolution,
        fileSize,
        date,
        device,
        lens,
        shutterSpeed,
        aperture,
        iso,
        focalLength,
        _timestamp: resolvedDate ? resolvedDate.getTime() : 0,
      };
    });

    return Promise.all(filePromises);
  });

  const nestedImages = await Promise.all(categoryPromises);
  const images = nestedImages.flat();

  // Sort descending chronologically (newest first)
  images.sort((a, b) => b._timestamp - a._timestamp);
  images.forEach((img) => delete img._timestamp);

  cachedGalleryImagesResult = images;
  return images;
}
